import React, { useState } from 'react'
import { FaCaretRight, FaMinus, FaPlus } from 'react-icons/fa';
import { Link } from 'react-router-dom'
import './HomeFaq.css';

const HomeFaq = () => {

    const toggleShowAns = (index) => {
        const newShowAns = [...showAns];
        newShowAns[index] = !newShowAns[index];
        setShowAns(newShowAns);
    }
    const Faqs = [
        {
            question: 'What services does your e-commerce website offer to farmers and agriculture enthusiasts?',
            answer: "Our e-commerce platform offers a wide range of services for the agriculture community. We provide solutions like pest scanning, soil nutrient analysis, laser weed elimination, and various other monitoring tools to help enhance agricultural productivity. Additionally, we offer advanced systems such as aquaponics and hydroponics, as well as different irrigation methods for users. We're also a marketplace where farmers can sell their products and where agriculture-related sellers can offer their products and services.",
        },
        {
            question:'How do your Machine Learning algorithms and datasets benefit users on your platform?',
            answer:"Our powerful server is integrated with Machine Learning algorithms and datasets. This means that we can provide data-driven insights and recommendations to users. Whether you're a farmer looking to optimize your crop yield or a buyer seeking the best agricultural products, our ML-based decision hub can help you make informed decisions and streamline your operations.",
        },
        {
            question:'Can you explain more about the community aspect of your platform where users, farmers, and experts can interact?',
            answer:"Certainly! We have a dedicated community space where users, farmers, and agriculture experts can come together. Here, you can discuss your experiences, share ideas, and seek advice from knowledgeable experts in the field. This collaborative environment allows for the exchange of valuable insights and fosters a sense of learning and growth within the agriculture community.",
        },
        {
            question:"How can I become a seller on your platform if I'm a farmer or offer agriculture-related products/services?",
            answer:"It's easy to become a seller on our platform. If you're a farmer, you can sign up as a seller and list your agricultural products for sale. If you're an agriculture-related seller, you can also join our platform and showcase your products and services to our user base. Our user-friendly interface and seller support team make the onboarding process smooth and hassle-free.",
        },
        {
            question:'What distinguishes your e-commerce platform from others in the market?',
            answer:"hat sets us apart is our comprehensive approach to agriculture. We not only offer a marketplace for buying and selling agricultural products but also provide a wide range of services, including pest scanning, soil nutrient analysis, laser weed elimination, and more. Our integration of Machine Learning ensures data-driven decision-making, and our community space fosters knowledge sharing and collaboration among users, farmers, and experts.",
        },
        {
            question:'Can you provide more details about the advanced agriculture systems you mentioned, like aquaponics and hydroponics?',
            answer:"Certainly! We offer advanced agriculture systems like aquaponics and hydroponics, which are innovative and sustainable methods for growing crops. Aquaponics combines aquaculture (raising fish) and hydroponics (cultivating plants in water) in a symbiotic system. Hydroponics, on the other hand, involves growing plants in nutrient-rich water, without soil. These systems are known for their efficiency and environmentally friendly approach to agriculture, and we can provide resources and support for those interested in adopting them.",
        },
        {
            question:'How can I access the data and insights generated by your Machine Learning algorithms?',
            answer:"Accessing the data and insights generated by our Machine Learning algorithms is straightforward. Our platform provides user-friendly dashboards and tools that allow you to view and interpret the data. Additionally, we offer regular reports and notifications to keep you informed about important insights, trends, and recommendations related to your specific agriculture needs. You can customize your preferences to receive the information that matters most to you.",
        },
    ];

    const [showAns, setShowAns] = useState(Array(Faqs.length).fill(false));
    return (
        <div className='home-container-content-faq'>
            <div className="home-container-content-faq-left">
                <h2>FAQs</h2>
                <p>
                    Discover answers to common questions and gain insights into our e-commerce platform's offerings and services. Explore the world of agriculture solutions, from pest scanning to advanced agricultural systems. We've compiled a list of frequently asked questions to help you navigate our platform and make the most of your agriculture journey. If you have any more questions, feel free to reach out, and we'll be happy to assist you.
                </p>
                <div className="links">
                    <Link to='/#'>Chat with Assistance<FaCaretRight/></Link>
                    <Link to='/community-forum'>Get your doubt to our Forum<FaCaretRight/></Link>
                </div>
            </div>
            <div className="home-container-content-faq-right">
                <ul>
                    {Faqs.map((faq, index) => (
                        <li key={index}>
                            <div className="top">
                                <p>{faq.question}</p>
                                <button onClick={() => toggleShowAns(index)}>{showAns[index] ? <FaPlus /> : <FaMinus />}</button>
                            </div>
                            {showAns[index] && (
                                <p>{faq.answer}</p>
                            )}
                        </li>
                    ))}
                </ul>
            </div>
        </div>
    )
}

export default HomeFaq